server:
  port: 8084

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**

        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotel/**,/staff/**

        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
              - Path=/rating/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
