server:
  port: 8082
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true  
management:
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    name: Hotel-Service
    description: Hotel Service for microservices
    version: 1.0.0
