server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
resilience4j:
  circuitbreaker:
    instances:
      RATINGSERVICE:
        baseConfig: default
info:
  app:
    name: user-service
    description: User Service for microservices
    version: 1.0.0
